routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Category;
use App\Model\ProductModel;
use App\Product;
use App\Product_Attribute;
use App\Province;
use App\Setting;
use App\Ps_lang;
use App\PublicModel;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;


Route::get('/', 'HomeController@index')->name('urlMain');


Route::group(['prefix' => '/', 'namespace' => 'Site'], function () {
    // product
    Route::get('/productMore/{slug?}', 'ProductControllers@productMore')->name('productMore');

    // shop
    Route::get('/addcart/{id}', 'ShopControllers@addcart')->name('addcart');
    Route::get('/seecart', 'ShopControllers@seecart')->name('seecart');
});


Route::get('/home', 'HomeController@index')->name('home');

//*********************USER PANEL ************
Route::middleware(['panel'])->group(function () {
    Route::prefix('user')->group(function () {
        Route::get('panel', 'UserController@index')->name('main.user.index');
        Route::get('panel/changepass', 'UserController@editepass')->name('main.user.changepass');
        Route::post('panel/updateInfoUser', 'UserController@updateInfoUser')->name('main.user.updateInfoUser');
        Route::get('panel/deleteAvatarUser', 'UserController@deleteAvatarUser')->name('main.user.deleteAvatarUser');
        Route::post('panel/changepass', 'UserController@updatePass')->name('main.user.changepass.save');
        Route::get('panel/allorder', 'UserController@allorder')->name('main.user.allorder');
        Route::get('panel/return', 'UserController@return')->name('main.user.return');
        Route::get('panel/love', 'UserController@love')->name('main.user.love');
        Route::get('panel/deleteAddress/{id}', 'UserController@deleteAddress')->name('deleteAddress');
        Route::post('panel/updateAddressUser/{id}', ['uses' => 'UserController@updateAddressUser'])->name('updateAddressUser');
        Route::get('panel/tickets','UserControlle@tickets')->name('user.tickets');
    });
});
//*********************USER PANEL ************

//================================Alaki Controller==============================
/*
Route::get('/convert', 'AlakiController@convertMyTableToProducts')->name('convert');
Route::get('/userconvert', 'AlakiController@userConvert')->name('userConvert');
Route::get('/userthreadconvert', 'AlakiController@userthreadConvert')->name('userthreadConvert');
Route::get('/usermessageconvert', 'AlakiController@usermessageConvert')->name('usermessageConvert');
Route::get('/convertMyTableToAddress', 'AlakiController@convertMyTableToAddress')->name('convertMyTableToAddress');
Route::get('/registeremailalaki', function (){
    $activation_code='12345678';
    return view('email.register',compact('activation_code'));
});
//*/


//==============================================================================
Route::get('/clear-cache', function () {
//    $exitCode = Artisan::call('optimize');
//    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

//==============================================================================


// categories route
Route::get('categories/{name}', 'CategryController@show')->name('category.show');
// Route::get('cat/{name}', 'CategryController@edit')->name('category.edit');
//Route::post('cat/{name}', 'CategryController@update')->name('category.update');
Route::get('slider/{id}', 'CategryController@slider')->name('slider.show');
Route::get('cat/{name}/{filter}', 'CategryController@filter')->name('category.show.filter');
Route::get('slider/{id}/{filter}', 'CategryController@slider_filter')->name('slider.show.filter');
Route::get('special', 'CategryController@special')->name('main.special');
Route::get('special/{filter}', 'CategryController@specialfilter')->name('main.special.filter');

//end categories route

//  Shop routes

//  end of Shop routes

//************************************ADMIN ROUTE **********************
Route::middleware(['admin'])->group(function () {
    Route::prefix('admin')->group(function () {
       Route::get('features/search')->name('admin.search.features');
        Route::get('features/search/{text}',function ($text){
            $result=\App\Feature_value::query()->where('value','like','%'.$text.'%')->limit(20)->get();
            return view('front.select_feature',['fs'=>$result]);
        });


        Route::post('admin.product.color.edit',function (\Illuminate\Http\Request $request){

            $product_color=\App\Product_Color::query()->find($request->color_id);

            if ((isset($request->color_count))){

                $product_color->count=$request->color_count;
                $product_color->save();
            }
            if (isset($request->color_price))
            {
                $product_color->price=$request->color_price;
                $product_color->save();
            }


            return back();

        })->name('admin.product.color.edit');
        Route::post('admin.product.color.add/{id}',function ($id,\Illuminate\Http\Request $request){
            if ((isset($request->color))&&(isset($request->color_count))&&(isset($request->color_price))){
                $product_color=new \App\Product_Color();
                $product_color->product_id=$id;
                $product=Product::query()->find($id);
                $product_color->color_id=$request->color;
                $product_color->price=$request->color_price;
                $product_color->count=$request->color_count;
                $isset=true;
                foreach ($product->colors as $color){
                    if ($request->color==$color->color_id)
                        $isset=false;
                }
                if ($isset)
                    $product_color->save();
            }

            return back();

        })->name('admin.product.color.add');


        //colors
        Route::get('colors','admin\ColorController@index')->name('admin.color.index');
        Route::post('colors/edit/{id}','admin\ColorController@edit')->name('admin.color.edit');
        Route::post('colors/add','admin\ColorController@add')->name('admin.color.add');


        //end colors


        //warranties
        Route::get('warranties','admin\WarrantyController@index')->name('admin.warranty.index');
        Route::post('warranty/edit/{id}','admin\WarrantyController@edit')->name('admin.warranty.edit');
        Route::post('warranty/add','admin\WarrantyController@add')->name('admin.warranty.add');


        //end warranties

        //product image
        Route::post('product/image/add/{product_id}','admin\ImageController@add_image')->name('admin.product.image.add');
        Route::get('product/image/delete/{id}','admin\ImageController@delete')->name('admin.product.image.delete');
        Route::get('product/image/setcover/{id}/{product}','admin\ImageController@set')->name('admin.product.image.set');

        //end product image


        Route::post('admin.product.warranty.add/{id}',function ($id,\Illuminate\Http\Request $request){
            $product=Product::query()->find($id);
            $isset=true;
            $w=new \App\Product_Warranty();
            $w->product_id=$id;
            $w->warranty_id=$request->warranty_id;
            $w->price=$request->warranty_price;
            foreach ($product->warranties as $warranty)
                if ($warranty->warranty_id==$request->warranty_id)
                    $isset=false;
            if ($isset)
                $w->save();
            return back();
        })->name('admin.product.warranty.add');

        Route::get('admin/product/feature/delete/{id}',function ($id){
            \App\Feature_Product::query()->find($id)->delete();
            return back();

        })->name('admin.product.feature.delete');


        Route::get('admin/product/warranty/delete/{id}',function ($id){
            $product_warranty=\App\Product_Warranty::query()->find($id);
            $product_warranty->delete();
            return back();
        })->name('admin.product.warranty.delete');


        Route::get('admin/product/color/delete/{id}',function ($id){
            $product_color=\App\Product_Color::query()->find($id);
            $product_color->delete();
            return back();
        })->name('admin.product.color.delete');



        Route::get('', function () {

            return view('admin.home');
        })->name('admin.home');
        Route::resource('products', 'admin\ProductController')->only([
            'create', 'show', 'store', 'index', 'update'
        ]);
        Route::get('product/add/store','admin\ProductController@step_add')->name('admin.product.add_store');

        Route::get('product/add/store/removecat')->name('admin.product.removecats');
        Route::get('product/add/store/removecat/{product}/{cat}',function ($product,$cat){
            $product=Product::query()->find($product);
            $category=\App\Product_category::query()->find($cat);
            $ok=false;
            if ($category->delete())
                $ok=true;
            $text='<tr class="success">';
            if (count($product->AllCategory)>0){
                foreach ($product->AllCategory as $cats){
                    $text.=' <td>'.$cats->category->name.'</td><td><button onclick="DeleteCat('.$product->id.','.$cats->id.')"><i class="fa fa-remove"></i></button></td>';

                }

                $text.='</tr>';
            }

            else
                $text='<tr>
 <div class="alert alert-danger">

app/Product.php
<?php

namespace App;

//use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
//    use Sluggable;



    protected $fillable = ['category_id', 'name', 'image', 'details', 'price_main', 'price_off', 'special', 'slug', 'active', 'position', 'totalSelling', 'latest', 'totalVisited', 'number','view'];

    public function specil(){
        return $this->hasOne('App\Special','product_id');
    }
    public function getRouteKeyName()
    {
        return 'slug';
    }
    public function attrs(){
        return $this->hasMany('App\Product_Attribute','id_product');
    }
    public function images(){
      return  $this->hasMany('App\Product_Image','id_product');
    }
    public function category(){
        return $this->belongsTo('App\Category','category_id');
    }
    public function AllCategory(){
        return $this->hasMany('App\Product_category','product_id');
    }
    public function features(){
        return $this->hasMany('App\Feature_Product','id_product');
    }
    public function special(){
        return $this->hasOne('App\Special','product_id');
    }
    public function comments(){
        return $this->hasMany('App\ProductComment','product_id');
    }

    public function warranties(){
   return $this->hasMany('App\Product_Warranty','product_id');
    }
    public function colors(){
        return $this->hasMany('App\Product_Color','product_id');
    }


}

app/Http/Controllers/Site/ProductControllers.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Site\UpdateCart;
use App\Product;
use App\PublicModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Session;

class ProductControllers extends Controller
{
    use UpdateCart;

    public function productMore($slug = null)
    {
        $updateallcarts = $this->updateAllCarts();
        $priceOfCarts = $updateallcarts[0];
        $numberOfCarts = $updateallcarts[1];

        $product = Product::where('slug', $slug)->first();

        return view('front.productMore', compact('product', 'numberOfCarts', 'priceOfCarts'));
    }
}

app/Http/Controllers/admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Attribute_Group;
use App\Count;
use App\Model\ProductModel;
use App\Product;
use App\Product_category;
use App\Product_Image;
use App\PublicModel;
use App\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{


    public function __construct()
    {
      //  session()->remove('product_store_id');
  // session(['product_store_id'=>10]);
    }

    public function index()
    {
        $products = Product::query()->orderByDesc('id')->paginate(20);
        $exhibition = Setting::where('name', 'exhibition')->first();
        return view('admin.product.index', ['products' => $products, 'exhibition' => $exhibition]);
    }

    public function exhibit(Request $request)
    {
        $exhibition = Setting::where('name', 'exhibition')->first();
        $val = 0;

        if ($request->chk == "true"){
            $val = 1;
        }
        $exhibition->update([
            'isActive' => $val ,
        ]);

        return response()->json([
            'data' => [
                'success' => true,
                'status' => $val
            ]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      /*  if (session()->has('product_store_id'))
         return view('admin.product.StepValidation');
        else*/
        return view('admin.product.create');
    }


    public function store(Request $request)
    {
        $keys = ['category_id', 'name', 'details','quantity', 'price_main', 'wholesale_price', 'number', 'meta_title', 'meta_keyword', 'meta_description', 'type', 'active', 'active_special', 'totalSelling', 'totalVisited'];
        $validatedData = $request->validate([
            'name' => 'required|unique:products',
            'wholesale_price' => 'nullable',
            'price_main' => 'required',
            'image' => 'required|image',
            'quantity'=>'required',
        ], ['name.required' => 'نام محصول الزامی می باشد!', 'name.unique' => 'این نام قبلا ثبت شد!', 'image.required' => 'فایل  تصویر الزامی است!!', 'image.image' => 'فایل  تصویر نمی باشد!', 'image.mimes' => 'فرمت تصویر باید jpg باشد']);

        $product = new Product();

        foreach ($keys as $key) {
            $this->setp($product, $key, $request);
        }

        $product->slug = str_replace(' ', '_', $request->name);
        $save = $product->save();


        if ($save) {
            $image = new Product_Image();
            $image->id_product = $product->id;
            $image->cover = 1;
            $model = new PublicModel();
            $file = $request->file('image');
            $filename = time().rand(0,100000). '.' . $file->getClientOriginalExtension();
            $image->url=$filename;
            $image->save();
            $file->move((new PublicModel())->public_image_folder, $filename);

            session()->flash('alert', '<div class="alert alert-success">محصول جدید با موفقیت ثبت شد!</div>');
            session(['product_store_id'=>$product->id]);
            return back();
        } else {
            session()->flash('alert', '<div class="alert alert-danger">خطای صورت گرفت!!</div>');
            return back();
        }

    }
    public function show($id)
    {
        $product = Product::query()->find($id);
        if ((new PublicModel())->isImpty($product))
            return redirect('404');


        return view('admin.product.show', ['product' => $product]);
    }
    public function edit($id)
    {
        //
    }
    public function update(Request $request, $id)
    {

        $keys = ['category_id', 'name','quantity', 'details', 'price_main', 'wholesale_price', 'number', 'meta_title', 'meta_keyword', 'meta_description', 'type', 'active', 'active_special', 'totalSelling', 'totalVisited'];
        $validatedData = $request->validate([
            'name' => 'required',
            'quantity'=>'required',
            'wholesale_price' => 'required',
            'price_main' => 'required',

        ], ['name.required' => 'نام محصول الزامی می باشد!']);

        $product = Product::query()->find($id);

        foreach ($keys as $key) {
            $this->setp($product, $key, $request);
        }

        $product->slug = str_replace(' ', '_', $request->name);
        //  return json_decode($request->cats);
        $save = $product->save();


        if ($save) {

            session()->flash('alert', '<div class="alert alert-success">محصول  با موفقیت ویرایش شد!</div>');
            return back();
        } else {
            session()->flash('alert', '<div class="alert alert-danger">خطای صورت گرفت!!</div>');
            return back();
        }
    }
    public function destroy($id)
    {
        //
    }
    public function setp($product, $value, $requst)
    {
        if (isset($requst[$value]))
            $product[$value] = $requst[$value];
    }
    public function special_add()
    {
        return view('admin.product.special');
    }
    public function all_comment($id){
        $product=Product::query()->find($id);
        $comments=$product->comments->where('deleted','=',0);
        return view('admin.product.comments',['comments'=>$comments,'product'=>$product]);
    }
    public function step_add(){
        if (session()->has('product_store_id'))
        return view('admin.product.multi-selection');
        return redirect(route('products.create'));
    }
    public function delete_session_product(){

        if (session()->has('product_store_id'))
            session()->remove('product_store_id');
        return redirect(route('products.create'));
    }
}

resources/views/admin/product/ajax_show.blade.php


<tr>
    <th>شماره
    </th>
    <th>نام
    </th>

    <th>تصویر</th>
    <th>تعداد</th>
    <th>قیمت</th>
    <th>نوع محصول</th>
    <th>مشاهده</th>
</tr>

<?php
if ($products!=null)
    if (count($products->get())>1)
        $products=$products->paginate(200);
    else
        $products=$products->get();


?>
@if($products!=null)
@foreach($products as $product)

    <tr>
        <td>{{$product->id}}</td>

        <td>{{$product->name}}</td>
        <td><img width="50" src="{{(new \App\PublicModel())->image_cover($product)}}"></td>
        <td>{{(new \App\PublicModel())->count($product)}}</td>
        <td>{{number_format($product->price_main)}}</td>
        <td>
            @if(count($product->attrs)>0)
                محصولات با ترکیبات
            @else
                محصول بدون ترکیب
            @endif
        </td>
        <td>
            <a href="{{route('products.show',['id'=>$product->id])}}" class="btn btn-sm btn-primary"><i class="fa fa-eye"></i></a>
        </td>
    </tr>
@endforeach

 @else
    <tr>
        <td class="alert alert-danger">محصولی یافت نشد</td>
    </tr>


@endif

resources/views/admin/product/attribute_select.blade.php
<div  style="height:200px;">
    <aside style="width: 100%" class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <ul class="sidebar-menu" data-widget="tree">

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-list-ol"></i> <span> انتخاب ویژگی</span>
                        <span class="pull-left-container">
                <i class="fa fa-angle-right pull-left"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        @foreach(\App\Attribute_Group::all() as $group)

                                <li class="treeview" >
                                    <a ><span style="cursor: pointer" class="badge"> {{$group->name}}</span>

                                        <span class="pull-left-container">

                                             <i class="fa fa-angle-right pull-left"></i>
                                        </span>
                                    </a>

                                    <ul style="overflow: scroll;max-height: 200px" class="treeview-menu">
                                        @foreach($group->attrs as $child)
                                            <?php $is=false;  ?>
                                            @foreach($attrs as $atrr)
                                                <?php if ($atrr->id==$child->id)
                                                    $is=true;
                                                ?>

                                            @endforeach
                                            @if(!$is)
                                                <li class="treeview">

                                                    <input  id="{{$child->id}}" type="radio" name="group{{$group->id}}" checked="" style="width:20px;display: inline" onchange="select_attr(this,this.id)"><span style="cursor: pointer" class="badge" > {{$child->value->name}}</span>

                                                    <span class="pull-left-container">
                                             <i class="fa fa-angle-right pull-left"></i>
                                            </span>
                                                    </a>

                                                </li>
                                            @else
                                                <li class="treeview">

                                                    <span style="cursor: pointer;background-color: green"  class="badge badge-success" > {{$child->value->name}}</span>

                                                    <span class="pull-left-container">
                                             <i class="fa fa-angle-right pull-left"></i>
                                            </span>
                                                    </a>

                                                </li>

                                            @endif


                                        @endforeach

                                    </ul>
                                </li>


                        @endforeach


                    </ul>


                </li>


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
</div>

resources/views/admin/product/category_select.blade.php
<div  style="height:200px;">
    <aside style="width: 100%" class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <ul class="sidebar-menu" data-widget="tree">

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-list-ol"></i> <span>دسته ها</span>
                        <span class="pull-left-container">
                <i class="fa fa-angle-right pull-left"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        @foreach(\App\Category::query()->where('parent_id','=',0)->get() as $category)
                            @if(empty($category->childs))
                                <li><a> <input id="{{$category->id}}" type="checkbox" style="display: inline" onchange="select_cat(this,'{{$category->id}}')">{{$category->name}}</a></li>
                            @else
                                <li class="treeview">
                                    <input id="{{$category->id}}" type="checkbox" style="display: inline" onchange="select_cat(this,'{{$category->id}}')">  <a style="cursor: pointer;display: inline"><span style="cursor: pointer" class="badge"> {{$category->name}}</span>

                                        <span class="pull-left-container">

                                             <i class="fa fa-angle-right pull-left"></i>
                                        </span>
                                    </a>
                                    @include('admin.product.childs1',['category'=>$category])
                                </li>
                            @endif

                        @endforeach


                    </ul>
                </li>


            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
</div>

resources/views/admin/product/temp.blade.php
<div class="col-md-10">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">افزودن محصول </h3>


            <!-- The actual snackbar -->


            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>


            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

            <div class="box box-primary">
                <div class="box-header with-border">

                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-group" role="form" enctype="multipart/form-data" method="post" action="{{route('products.store')}}">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">نام محصول</label>
                            <input name="name" value="{{old('name')}}" type="text" class="form-control" id="exampleInputEmail1" placeholder="نام محصول">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">دسته بندی پیشفرض</label>
                            <select name="category_id" type="text" class="form-control" id="exampleInputEmail1" >
                                @foreach(\App\Category::query()->where('active','=',1)->get() as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>

                                @endforeach
                            </select>
                        </div>
                        <!-- Trigger the modal with a button -->
                        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">دسته های مرتبط</button>
                        <div class="form-group">
                            <label for="exampleInputEmail1">خلاصه ویژگی ها</label>


                            <div class="box box-success">
                                <div class="box-header">

                                    <!-- tools box -->
                                    <div class="pull-right box-tools">

                                    </div>
                                    <!-- /. tools -->
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body pad">

                  <textarea  id="details" name="editor1" rows="10"
                             cols="80"></textarea>

                                </div>
                            </div>

                        </div>
                        <br>

                        <div class="form-group">
                            <label for="exampleInputEmail1">تعداد محصول</label>
                            <input name="quantity" type="text" class="form-control" id="exampleInputEmail1" placeholder="تعداد محصول">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">قیمت اصلی (پرداختی)</label>
                            <input name="price_main" type="text" class="form-control" id="exampleInputEmail1" placeholder="قیمت محصول">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">قیمت با مالیات (اختیاری)</label>
                            <input name="wholesale_price" type="text" class="form-control" id="exampleInputEmail1" placeholder="قیمت با مالیات محصول">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">عنوان متا (اختیاری)</label>
                            <input name="meta_title" type="text" class="form-control" id="exampleInputEmail1" >
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">کلمات متا (اختیاری)</label>
                            <input name="meta_keyword" type="text" class="form-control" id="exampleInputEmail1" >
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">توضیحات متا (اختیاری)</label>
                            <input name="meta_description" type="text" class="form-control" id="exampleInputEmail1" >
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">توضیحات متا (اختیاری)</label>
                            <input name="meta_description" type="text" class="form-control" id="exampleInputEmail1" >
                        </div>




                        <div class="form-group">
                            <label for="exampleInputEmail1">عکس اصلی محصول</label>
                            <input name="image" type="file" class="form-control" id="exampleInputEmail1" >
                        </div>
                        <input type="hidden" name="cats" id="cats_id">


                        <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Modal Header</h4>
                                    </div>
                                    <div class="modal-body" style="overflow: scroll;height: 90%">
                                        @include('admin.product.category_select')
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="form-group">
                        <label for="exampleInputEmail1">نوع محصول</label>
                        <select required="required">
                            <option>1</option>
                            <option>2</option>
                        </select>
                    </div>

                    <input type="hidden" name="cats" id="cats_id">
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">افزودن</button>
                    </div>
                </form>
            </div>
            <!-- /.row -->
        </div>
        <!-- ./box-body -->
        <div class="box-footer">

        </div>
        <!-- /.box-footer -->
    </div>
    <!-- /.box -->
</div>
<!-- /.col -->